# Generated by Django 3.2.7 on 2021-09-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages_participants_room_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Chat_User',
        ),
    ]
